/* 敵からの取得アイテム */
CREATE TABLE DROP_ITEMS(
	ID INT PRIMARY KEY,
	NAME VARCHAR(255),
	REQUIRE_LEVEL INT,
	ENEMY_NAME VARCHAR(255));
CREATE INDEX ON DROP_ITEMS(NAME);
CREATE INDEX ON DROP_ITEMS(REQUIRE_LEVEL);
/* 採取アイテム */
CREATE TABLE GATHERING_ITEMS(
	ID INT PRIMARY KEY,
	NAME VARCHAR(255),
	REQUIRE_LEVEL INT,
	REQUIRE_GATHERER_CLASS VARCHAR(255));
CREATE INDEX ON GATHERING_ITEMS(NAME);
CREATE INDEX ON GATHERING_ITEMS(REQUIRE_LEVEL);
/* 場所 */
CREATE TABLE SPOTS(
	ID INT PRIMARY KEY,
	NAME VARCHAR(255),
	X INT,
	Y INT);
/* 敵からの取得アイテムと場所の関連 */
CREATE TABLE DROP_ITEM_SPOT_RELATIONS(
	DROP_ITEMS_ID INT,
	SPOT_ID INT,
	PRIMARY KEY(DROP_ITEMS_ID, SPOT_ID));
/* 採取アイテムと場所の関連 */
CREATE TABLE GATHERING_ITEM_SPOT_RELATIONS(
	GATHERING_ITEM_ID INT,
	SPOT_ID INT,
	PRIMARY KEY(GATHERING_ITEM_ID, SPOT_ID));
/* サンプルデータ */
INSERT INTO DROP_ITEMS VALUES
(1, 'アプカレの卵', 16, 'アプカレ'),
(2, 'ダイアマイクの腱', 25, 'ベーンマイク'),
(3, 'ペイスタの粗皮', 49, 'バジリスタ');
INSERT INTO GATHERING_ITEMS VALUES
(1, '鉄鋼', 11, '採掘師'),
(2, 'アップル', 41, '園芸師'),
(3, 'ブローフィッシュ', 22, '釣り師');
INSERT INTO SPOTS VALUES
(1, '東部森林', 13, 20),
(2, '鉱山前', 16, 2),
(3, '南部平原', 30, 25),
(4, '砂漠', 21, 19);
INSERT INTO DROP_ITEM_SPOT_RELATIONS VALUES
(1, 1),
(1, 3),
(2, 1),
(3, 2),
(3, 4);
INSERT INTO GATHERING_ITEM_SPOT_RELATIONS VALUES
(1, 2),
(2, 1),
(2, 3),
(3, 1);
